CREATE TABLE drinkstreet.event
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE drinkstreet.product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    basic_price DOUBLE PRECISION,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE drinkstreet.selling
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT,
    seller_id  BIGINT,
    event_id   BIGINT,
    CONSTRAINT pk_selling PRIMARY KEY (id)
);